package CustomerGui;

import Objects.InvItem;
import java.awt.Color;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author LENOVO
 */
public class ItemReciept extends javax.swing.JPanel {
    
    InvItem item;
    Cart cart;
    
    public ItemReciept(InvItem item, Cart cart) {
        this.item = item;
        this.cart = cart;

        initComponents();
        
        this.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 60));
        this.setPreferredSize(new java.awt.Dimension(647, 60));
        this.setMinimumSize(new java.awt.Dimension(647, 60));
        this.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        this.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(243,243,243)));
        
        EventQueue.invokeLater(()-> initDesign());
    }

    private void initDesign() {
        // Set dynamic size for scroll container compatibility
        this.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 60));
        this.setPreferredSize(new java.awt.Dimension(647, 60));

        jLabel1.setText(item.getItem());
        jLabel2.setText(String.valueOf(item.getQuantity()));
        jLabel5.setText(String.valueOf(item.getPrice()));
        
        // fuctionality of the remove button
        jLabel3.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (JOptionPane.showConfirmDialog(cart, "Are you sure?", "Item Removal", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {
                    cart.store.cartItems.remove(item);
                    cart.loadCart();
//                    System.out.println(cart.store.cartItems);
                }
            }
            
            public void mouseEntered(MouseEvent e) { jLabel3.setFont(new Font("Montserrat", 1, 12)); }
            public void mouseExited(MouseEvent e) { jLabel3.setFont(new Font("Montserrat", 0, 12)); }
        });
        
        // funtionality of the add button
        jLabel4.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                
            }
            
            public void mouseEntered(MouseEvent e) { jLabel4.setFont(new Font("Montserrat", 1, 12)); }
            public void mouseExited(MouseEvent e) { jLabel4.setFont(new Font("Montserrat", 0, 12)); }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(361, 59));
        setMinimumSize(new java.awt.Dimension(361, 59));
        setPreferredSize(new java.awt.Dimension(361, 59));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 100, 100));
        jLabel1.setText("PLACEHOLDER TEXT");

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(100, 100, 100));
        jLabel2.setText("QUANTITY");

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(224, 82, 83));
        jLabel3.setText("REMOVE");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(100, 100, 100));
        jLabel4.setText("ADD");

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(100, 100, 100));
        jLabel5.setText("PRICE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
