package CustomerGui;

import Database.DBHandler;
import Objects.InvItem;
import Objects.User;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author LENOVO
 */
public class Store extends javax.swing.JPanel {

    DBHandler db = new DBHandler();
    User user;
    
    private ArrayList<InvItem> items;
    private ArrayList<itemPane> storeItems = new ArrayList<>();
    
    public ArrayList<InvItem> cartItems = new ArrayList<>();
    
    public Store(User user) {
        initComponents();
        this.user = user;
        EventQueue.invokeLater(() -> {initDesign();
            jScrollPane2.getViewport().addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent evt){
                    initDesign();
                }
            });
            jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        });
    }

    private void initDesign() {
        // Set FlowLayout with LEFT alignment and spacing
        jPanel1.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));

        // Clear previous items if re-rendering
        jPanel1.removeAll();
        storeItems.clear();

        // Generate and add items
        generateItems();

        for (itemPane storeItem : storeItems) {
            storeItem.setPreferredSize(new Dimension(230, 300)); // fixed size for each item
            jPanel1.add(storeItem);
        }

        // Estimate number of items per row based on current viewport width
        int viewportWidth = jScrollPane2.getViewport().getWidth();
        int itemsPerRow = viewportWidth / 240; // 230 width + 10px spacing
        if (itemsPerRow < 1) itemsPerRow = 1;

        // Calculate required height for jPanel1 based on number of rows
        int rowCount = (int) Math.ceil((double) storeItems.size() / itemsPerRow);
        int totalHeight = rowCount * 310; // 300 height + 10 spacing

        // Set preferred size for scroll content panel
        jPanel1.setPreferredSize(new Dimension(viewportWidth, totalHeight));

        // Repaint and revalidate to apply changes
        jPanel1.revalidate();
        jPanel1.repaint();
    }


    private void generateItems() {
        items = db.getInventory();

        if (items == null) {
            System.out.println("Error: Inventory or gallery is null.");
            return;
        }

        for (int i = 0; i < items.size(); i++) {
            InvItem item = items.get(i);

            if (item != null) {
                itemPane pane = new itemPane(item, this);
                storeItems.add(pane);
            } else {
                System.out.println("Missing data for item index: " + i);
            }
        }
    }
    
    public void addToCart(InvItem purchase, int quantity){
        purchase.setQuantity(quantity);
        purchase.setPrice(purchase.getPrice()*quantity);
        
        cartItems.add(purchase);
        JOptionPane.showMessageDialog(null, "Sucessfully added "+ purchase.getItem(), "Item Added", JOptionPane.INFORMATION_MESSAGE);
//        System.out.println(cartItems);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(243, 243, 243));

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
