package CustomerGui;

import Database.DBHandler;
import Objects.InvItem;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import javax.swing.JScrollPane;

/**
 *
 * @author LENOVO
 */
public class Store extends javax.swing.JPanel {

    DBHandler db = new DBHandler();
    
    private ArrayList<InvItem> items;
    private ArrayList<Image> gallery;
    private ArrayList<itemPane> storeItems = new ArrayList<>();
    
    public ArrayList<InvItem> cartItems = new ArrayList<>();
    
    public Store() {
        initComponents();
        EventQueue.invokeLater(() -> {initDesign();
            jScrollPane2.getViewport().addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent evt){
                    initDesign();
                }
            });
            jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        });
    }

    private void initDesign() {
        // Set FlowLayout with LEFT alignment and spacing
        jPanel1.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));

        // Clear previous items if re-rendering
        jPanel1.removeAll();
        storeItems.clear();

        // Generate and add items
        generateItems();

        for (itemPane storeItem : storeItems) {
            storeItem.setPreferredSize(new Dimension(230, 300)); // fixed size for each item
            jPanel1.add(storeItem);
        }

        // Estimate number of items per row based on current viewport width
        int viewportWidth = jScrollPane2.getViewport().getWidth();
        int itemsPerRow = viewportWidth / 240; // 230 width + 10px spacing
        if (itemsPerRow < 1) itemsPerRow = 1;

        // Calculate required height for jPanel1 based on number of rows
        int rowCount = (int) Math.ceil((double) storeItems.size() / itemsPerRow);
        int totalHeight = rowCount * 310; // 300 height + 10 spacing

        // Set preferred size for scroll content panel
        jPanel1.setPreferredSize(new Dimension(viewportWidth, totalHeight));

        // Repaint and revalidate to apply changes
        jPanel1.revalidate();
        jPanel1.repaint();
    }


    private void generateItems() {
        items = db.getInventory();
        gallery = db.getInventoryImage();

        if (items == null || gallery == null) {
            System.out.println("Error: Inventory or gallery is null.");
            return;
        }

        for (int i = 0; i < items.size(); i++) {
            Image image = (i < gallery.size()) ? gallery.get(i) : null;
            InvItem item = items.get(i);

            if (image != null && item != null) {
                itemPane pane = new itemPane(image, item, this);
                storeItems.add(pane);
            } else {
                System.out.println("Missing data for item index: " + i);
            }
        }
    }
    
    public void addToCart(InvItem purchase, int quantity){
        purchase.setQuantity(quantity);
        purchase.setPrice(purchase.getPrice()*quantity);
        
        cartItems.add(purchase);
        
        System.out.println(cartItems);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(243, 243, 243));

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel1);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(100, 100, 100));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 82, 83), 1, true));
        jTextField1.setPreferredSize(new java.awt.Dimension(500, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
